// <auto-generated />
// Run python3 scripts/generate-wire.py; do not edit.
namespace ShieldLabs.Internal;

internal sealed class WireDetectionFlags
{
    internal static readonly WireField<bool> Abuser = new WireField<bool>("abuser");
    internal static readonly WireField<bool> AntiDetectBrowser = new WireField<bool>("anti_detect_browser");
    internal static readonly WireField<bool> BrowserAutomation = new WireField<bool>("browser_automation");
    internal static readonly WireField<bool> BrowserVpnProxy = new WireField<bool>("browser_vpn_proxy");
    internal static readonly WireField<bool> CheckIncomplete = new WireField<bool>("check_incomplete");
    internal static readonly WireField<bool> DatacenterIp = new WireField<bool>("datacenter_ip");
    internal static readonly WireField<bool> Incognito = new WireField<bool>("incognito");
    internal static readonly WireField<bool> IpMismatch = new WireField<bool>("ip_mismatch");
    internal static readonly WireField<bool> JavascriptDisabled = new WireField<bool>("javascript_disabled");
    internal static readonly WireField<bool> OsMismatch = new WireField<bool>("os_mismatch");
    internal static readonly WireField<bool> OsNotDetected = new WireField<bool>("os_not_detected");
    internal static readonly WireField<bool> PrivacyRelay = new WireField<bool>("privacy_relay");
    internal static readonly WireField<bool> Proxy = new WireField<bool>("proxy");
    internal static readonly WireField<bool> SearchBot = new WireField<bool>("search_bot");
    internal static readonly WireField<bool> StunNotChecked = new WireField<bool>("stun_not_checked");
    internal static readonly WireField<bool> SuspiciousPaidClick = new WireField<bool>("suspicious_paid_click");
    internal static readonly WireField<bool> TimezoneMismatch = new WireField<bool>("timezone_mismatch");
    internal static readonly WireField<bool> Tor = new WireField<bool>("tor");
    internal static readonly WireField<bool> Vpn = new WireField<bool>("vpn");
}

internal sealed class WireDomainProfile
{
    internal static readonly WireField<string> Callback = new WireField<string>("Callback");
    internal static readonly WireField<string> CreatedAt = new WireField<string>("CreatedAt");
    internal static readonly WireField<string> Domain = new WireField<string>("Domain");
    internal static readonly WireField<string> PublicKey = new WireField<string>("PublicKey");
    internal static readonly WireField<string> Secret = new WireField<string>("Secret");
    internal static readonly WireField<long> Weight = new WireField<long>("Weight");
}

internal sealed class WireErrorBody
{
    internal static readonly WireField<string> Error = new WireField<string>("error");
}

internal sealed class WireHealthStatus
{
    internal static readonly WireField<string> Status = new WireField<string>("status");
}

internal sealed class WireHistoryPage
{
    internal static readonly WireField<WireArray<WireHistoryRow>> Data = new WireField<WireArray<WireHistoryRow>>("data");
    internal static readonly WireField<long> Total = new WireField<long>("total");
}

internal sealed class WireHistoryRow
{
    internal static readonly WireField<string> Browser = new WireField<string>("browser");
    internal static readonly WireField<bool> CheckIncomplete = new WireField<bool>("check_incomplete");
    internal static readonly WireField<string> ClickIdType = new WireField<string>("click_id_type");
    internal static readonly WireField<string> ConnectionType = new WireField<string>("connection_type");
    internal static readonly WireField<string> CookieId = new WireField<string>("cookie_id");
    internal static readonly WireField<string> Country = new WireField<string>("country");
    internal static readonly WireField<string> CreatedAt = new WireField<string>("created_at");
    internal static readonly WireField<string> DeviceId = new WireField<string>("device_id");
    internal static readonly WireField<string> DeviceType = new WireField<string>("device_type");
    internal static readonly WireField<string> Domain = new WireField<string>("domain");
    internal static readonly WireField<string> EntryUrl = new WireField<string>("entry_url");
    internal static readonly WireField<string> Ip = new WireField<string>("ip");
    internal static readonly WireField<bool> IsAbuser = new WireField<bool>("is_abuser");
    internal static readonly WireField<bool> IsAntidetect = new WireField<bool>("is_antidetect");
    internal static readonly WireField<bool> IsBrowserAutomation = new WireField<bool>("is_browser_automation");
    internal static readonly WireField<bool> IsDatacenter = new WireField<bool>("is_datacenter");
    internal static readonly WireField<bool> IsIncognito = new WireField<bool>("is_incognito");
    internal static readonly WireField<bool> IsJsDisabled = new WireField<bool>("is_js_disabled");
    internal static readonly WireField<bool> IsOsMismatch = new WireField<bool>("is_os_mismatch");
    internal static readonly WireField<bool> IsOsNotDetected = new WireField<bool>("is_os_not_detected");
    internal static readonly WireField<bool> IsPrivacyRelay = new WireField<bool>("is_privacy_relay");
    internal static readonly WireField<bool> IsProxy = new WireField<bool>("is_proxy");
    internal static readonly WireField<bool> IsSearchBot = new WireField<bool>("is_search_bot");
    internal static readonly WireField<bool> IsStunNotChecked = new WireField<bool>("is_stun_not_checked");
    internal static readonly WireField<bool> IsSuspiciousPaidClick = new WireField<bool>("is_suspicious_paid_click");
    internal static readonly WireField<bool> IsTimezoneMismatch = new WireField<bool>("is_timezone_mismatch");
    internal static readonly WireField<bool> IsTor = new WireField<bool>("is_tor");
    internal static readonly WireField<bool> IsVpn = new WireField<bool>("is_vpn");
    internal static readonly WireField<string> Os = new WireField<string>("os");
    internal static readonly WireField<string> ReferrerDomain = new WireField<string>("referrer_domain");
    internal static readonly WireField<string> RequestId = new WireField<string>("request_id");
    internal static readonly WireField<long> Score = new WireField<long>("score");
    internal static readonly WireField<string> ScoreDetails = new WireField<string>("score_details");
    internal static readonly WireField<string> SessionId = new WireField<string>("session_id");
    internal static readonly WireField<string> SiteDomain = new WireField<string>("site_domain");
    internal static readonly WireField<string> TrafficChannel = new WireField<string>("traffic_channel");
    internal static readonly WireField<string> TrafficChannelGroup = new WireField<string>("traffic_channel_group");
    internal static readonly WireField<string> TrafficReason = new WireField<string>("traffic_reason");
    internal static readonly WireField<string> UserHid = new WireField<string>("user_hid");
    internal static readonly WireField<string> UtmCampaign = new WireField<string>("utm_campaign");
    internal static readonly WireField<string> UtmContent = new WireField<string>("utm_content");
    internal static readonly WireField<string> UtmMedium = new WireField<string>("utm_medium");
    internal static readonly WireField<string> UtmSource = new WireField<string>("utm_source");
    internal static readonly WireField<string> UtmTerm = new WireField<string>("utm_term");
    internal static readonly WireField<long> Ver = new WireField<long>("ver");
    internal static readonly WireField<string> VisitorId = new WireField<string>("visitor_id");
    internal static readonly WireField<string> WebRtcConnectionType = new WireField<string>("web_rtc_connection_type");
    internal static readonly WireField<string> WebRtcCountry = new WireField<string>("web_rtc_country");
    internal static readonly WireField<string> WebRtcIp = new WireField<string>("web_rtc_ip");
    internal static readonly WireField<string> WebrtcLeakConnectionType = new WireField<string>("webrtc_leak_connection_type");
    internal static readonly WireField<string> WebrtcLeakCountry = new WireField<string>("webrtc_leak_country");
    internal static readonly WireField<string> WebrtcLeakIp = new WireField<string>("webrtc_leak_ip");
    internal static readonly WireField<string> WebrtcLeakSource = new WireField<string>("webrtc_leak_source");
}

internal sealed class WireIdentificationScoredData
{
    internal static readonly WireField<string> Browser = new WireField<string>("browser");
    internal static readonly WireField<string> ConnectionType = new WireField<string>("connection_type");
    internal static readonly WireField<string> CookieId = new WireField<string>("cookie_id");
    internal static readonly WireField<WireDetectionFlags> DetectionFlags = new WireField<WireDetectionFlags>("detection_flags");
    internal static readonly WireField<string> DeviceId = new WireField<string>("device_id");
    internal static readonly WireField<string> DeviceType = new WireField<string>("device_type");
    internal static readonly WireField<string> Domain = new WireField<string>("domain");
    internal static readonly WireField<WireIpInfo> LocalIp = new WireField<WireIpInfo>("local_ip");
    internal static readonly WireField<string> ObservedAt = new WireField<string>("observed_at");
    internal static readonly WireField<string> Os = new WireField<string>("os");
    internal static readonly WireField<WireIpInfo> PublicIp = new WireField<WireIpInfo>("public_ip");
    internal static readonly WireField<string> RequestId = new WireField<string>("request_id");
    internal static readonly WireField<long> RiskScore = new WireField<long>("risk_score");
    internal static readonly WireField<string> SessionId = new WireField<string>("session_id");
    internal static readonly WireField<WireArray<WireSignal>> Signals = new WireField<WireArray<WireSignal>>("signals");
    internal static readonly WireField<WireTrafficSource> TrafficSource = new WireField<WireTrafficSource>("traffic_source");
    internal static readonly WireField<string> UserHid = new WireField<string>("user_hid");
    internal static readonly WireField<string> VisitorId = new WireField<string>("visitor_id");
}

internal sealed class WireIdentificationScoredEvent
{
    internal static readonly WireField<string> CreatedAt = new WireField<string>("created_at");
    internal static readonly WireField<WireIdentificationScoredData> Data = new WireField<WireIdentificationScoredData>("data");
    internal static readonly WireField<string> EventType = new WireField<string>("event_type");
    internal static readonly WireField<string> SchemaVersion = new WireField<string>("schema_version");
}

internal sealed class WireIpInfo
{
    internal static readonly WireField<string> Country = new WireField<string>("country");
    internal static readonly WireField<string> Ip = new WireField<string>("ip");
}

internal sealed class WireLegacySnapshot
{
    internal static readonly WireField<string> Browser = new WireField<string>("Browser");
    internal static readonly WireField<string> ConnectionType = new WireField<string>("ConnectionType");
    internal static readonly WireField<string> CookieID = new WireField<string>("CookieID");
    internal static readonly WireField<string> Country = new WireField<string>("Country");
    internal static readonly WireField<WireArray<WireScoreDetail>> Details = new WireField<WireArray<WireScoreDetail>>("Details");
    internal static readonly WireField<string> DeviceID = new WireField<string>("DeviceID");
    internal static readonly WireField<string> DeviceType = new WireField<string>("DeviceType");
    internal static readonly WireField<string> IP = new WireField<string>("IP");
    internal static readonly WireField<string> LastRequestTime = new WireField<string>("LastRequestTime");
    internal static readonly WireField<string> OS = new WireField<string>("OS");
    internal static readonly WireField<string> RequestID = new WireField<string>("RequestID");
    internal static readonly WireField<long> Score = new WireField<long>("Score");
    internal static readonly WireField<string> SessionID = new WireField<string>("SessionID");
    internal static readonly WireField<string> UserHID = new WireField<string>("UserHID");
    internal static readonly WireField<string> VisitorID = new WireField<string>("VisitorID");
    internal static readonly WireField<string> WebRtcConnectionType = new WireField<string>("WebRtcConnectionType");
    internal static readonly WireField<string> WebRtcCountry = new WireField<string>("WebRtcCountry");
    internal static readonly WireField<string> WebRtcHIP = new WireField<string>("WebRtcHIP");
}

internal sealed class WireScoreDetail
{
    internal static readonly WireField<string> Description = new WireField<string>("Description");
    internal static readonly WireField<long> Value = new WireField<long>("Value");
}

internal sealed class WireSignal
{
    internal static readonly WireField<string> Name = new WireField<string>("name");
    internal static readonly WireField<long> Weight = new WireField<long>("weight");
}

internal sealed class WireTrafficSource
{
    internal static readonly WireField<string> Channel = new WireField<string>("channel");
    internal static readonly WireField<string> ClickIdType = new WireField<string>("click_id_type");
    internal static readonly WireField<string> LandingUrl = new WireField<string>("landing_url");
    internal static readonly WireField<string> ReferrerDomain = new WireField<string>("referrer_domain");
    internal static readonly WireField<string> UtmCampaign = new WireField<string>("utm_campaign");
    internal static readonly WireField<string> UtmContent = new WireField<string>("utm_content");
    internal static readonly WireField<string> UtmMedium = new WireField<string>("utm_medium");
    internal static readonly WireField<string> UtmSource = new WireField<string>("utm_source");
    internal static readonly WireField<string> UtmTerm = new WireField<string>("utm_term");
}

internal sealed class WireWebhookPingEvent
{
    internal static readonly WireField<string> CreatedAt = new WireField<string>("created_at");
    internal static readonly WireField<string> EventType = new WireField<string>("event_type");
    internal static readonly WireField<string> SchemaVersion = new WireField<string>("schema_version");
}

internal sealed class WireSearchHistoryParameters
{
    internal static readonly WireField<long> Limit = new WireField<long>("limit");
    internal static readonly WireField<long> Offset = new WireField<long>("offset");
    internal static readonly WireField<string> SearchType = new WireField<string>("search_type");
    internal static readonly WireField<string> Value = new WireField<string>("value");
}

internal static class WireSearchHistoryValues
{
    internal const string SearchTypeRequestId = "request_id";
    internal const string SearchTypeDeviceId = "device_id";
    internal const string SearchTypeUserHid = "user_hid";
    internal const string SearchTypeVisitorId = "visitor_id";
    internal const string SearchTypeIp = "ip";
    internal const string SearchTypeSessionId = "session_id";
    internal const string SearchTypeCookieId = "cookie_id";
}

internal sealed class WireSearchHistoryResponse
{
    internal static readonly WireField<WireArray<WireHistoryRow>> Data = new WireField<WireArray<WireHistoryRow>>("data");
    internal static readonly WireField<long> Total = new WireField<long>("total");
}

internal sealed class WireGetDomainProfileParameters
{
    internal static readonly WireField<string> XShieldDomain = new WireField<string>("X-Shield-Domain");
}

internal static class WireGetDomainProfileValues
{
}

internal sealed class WireGetDomainProfileResponse
{
    internal static readonly WireField<string> Callback = new WireField<string>("Callback");
    internal static readonly WireField<string> CreatedAt = new WireField<string>("CreatedAt");
    internal static readonly WireField<string> Domain = new WireField<string>("Domain");
    internal static readonly WireField<string> PublicKey = new WireField<string>("PublicKey");
    internal static readonly WireField<string> Secret = new WireField<string>("Secret");
    internal static readonly WireField<long> Weight = new WireField<long>("Weight");
}

internal sealed class WireIdentificationScoredBody
{
    internal static readonly WireField<string> CreatedAt = new WireField<string>("created_at");
    internal static readonly WireField<WireIdentificationScoredData> Data = new WireField<WireIdentificationScoredData>("data");
    internal static readonly WireField<string> EventType = new WireField<string>("event_type");
    internal static readonly WireField<string> SchemaVersion = new WireField<string>("schema_version");
}

internal sealed class WireWebhookPingBody
{
    internal static readonly WireField<string> CreatedAt = new WireField<string>("created_at");
    internal static readonly WireField<string> EventType = new WireField<string>("event_type");
    internal static readonly WireField<string> SchemaVersion = new WireField<string>("schema_version");
}
