#!/usr/bin/env python3
"""Generate the tolerant SDK's typed JSON fields from its bundled OpenAPI document."""
import argparse
import json
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/ShieldLabs/Internal/WireContract.g.cs"


class UnsupportedContract(ValueError):
    """The hand-maintained transport/parser must be updated before generating this contract."""


# These are transport capabilities, not duplicated response models. Reject changes that the
# supported client cannot send correctly; never silently emit unused required parameters.
TRANSPORT = {
    "searchHistory": ("/api/v1/history/{search_type}/{value}",
                      {"search_type": "path", "value": "path", "limit": "query", "offset": "query"}),
    "getDomainProfile": ("/v1/profile", {"X-Shield-Domain": "header"}),
}


def identifier(value):
    result = "".join(word[:1].upper() + word[1:] for word in re.split(r"[^a-zA-Z0-9]+", value) if word)
    if not result or result[0].isdigit():
        raise ValueError(f"Unsupported C# identifier: {value}")
    return result


def generate(document):
    def resolve(schema):
        seen = set()
        while "$ref" in schema:
            ref = schema["$ref"]
            if not ref.startswith("#/") or ref in seen:
                raise ValueError(f"Unsupported reference: {ref}")
            seen.add(ref)
            target = document
            for part in ref[2:].split("/"):
                target = target[part.replace("~1", "/").replace("~0", "~")]
            schema = {**target, **{k: v for k, v in schema.items() if k != "$ref"}}
        return schema

    def kind(schema):
        ref = schema.get("$ref", "")
        schema = resolve(schema)
        types = schema.get("type")
        if isinstance(types, list):
            types = [t for t in types if t != "null"]
            if len(types) != 1:
                raise ValueError(f"Unsupported union: {types}")
            types = types[0]
        if types == "array":
            return f"WireArray<{kind(schema['items'])}>"
        if types == "object":
            if not ref.startswith("#/components/schemas/"):
                raise ValueError("Object fields must reference a named schema")
            return "Wire" + identifier(ref.split("/")[-1])
        names = {"string": "string", "integer": "long", "number": "double", "boolean": "bool"}
        if types not in names:
            raise ValueError(f"Unsupported schema type: {types}")
        return names[types]

    lines = ["// <auto-generated />", "// Run python3 scripts/generate-wire.py; do not edit.", "namespace ShieldLabs.Internal;", ""]

    def fields(name, properties):
        lines.extend([f"internal sealed class Wire{name}", "{"])
        used = set()
        for key, schema in sorted(properties.items()):
            member = identifier(key)
            if member in used:
                raise ValueError(f"Duplicate member in {name}: {member}")
            used.add(member)
            field_type = kind(schema)
            lines.append(f"    internal static readonly WireField<{field_type}> {member} = new WireField<{field_type}>({json.dumps(key)});")
        lines.extend(["}", ""])

    # Generate every declared object, not a handwritten list of consumed columns.
    for name, schema in sorted(document["components"]["schemas"].items()):
        schema = resolve(schema)
        if schema.get("type") == "object":
            fields(identifier(name), schema.get("properties", {}))

    seen_operations = set()
    for route, path in document["paths"].items():
        for method, operation in path.items():
            if method != "get" or operation["operationId"] not in TRANSPORT:
                continue
            operation_id = operation["operationId"]
            expected_route, locations = TRANSPORT[operation_id]
            if route != expected_route or operation_id in seen_operations:
                raise UnsupportedContract(f"{operation_id}: unsupported route {route}; update the SDK transport")
            seen_operations.add(operation_id)
            name = identifier(operation_id)
            # Operation parameters override inherited parameters by (name, location), per OpenAPI.
            effective = {}
            for parameter in path.get("parameters", []) + operation.get("parameters", []):
                parameter = resolve(parameter)
                effective[(parameter["name"], parameter["in"])] = parameter
            for parameter in effective.values():
                key = parameter["name"]
                if key in locations and parameter["in"] != locations[key]:
                    raise UnsupportedContract(f"{operation_id}: {key} must be in {locations[key]}; update the SDK transport")
                if key not in locations and parameter.get("required", False):
                    raise UnsupportedContract(f"{operation_id}: unsupported required parameter {key}; update the SDK transport")
            # New optional parameters are deliberately not sent until exposed by the client.
            parameters = [p for p in effective.values() if p["name"] in locations]
            fields(name + "Parameters", {p["name"]: p["schema"] for p in parameters})
            lines.extend([f"internal static class Wire{name}Values", "{"])
            for parameter in parameters:
                schema = resolve(parameter["schema"])
                for value in schema.get("enum", []):
                    lines.append(f"    internal const string {identifier(parameter['name'])}{identifier(value)} = {json.dumps(value)};")
            lines.extend(["}", ""])
            response = resolve(operation["responses"]["200"])["content"]["application/json"]["schema"]
            fields(name + "Response", resolve(response)["properties"])
    if seen_operations != set(TRANSPORT):
        raise UnsupportedContract("Missing supported GET operation; update the SDK transport")
    envelopes = {}
    for name, hook in document["webhooks"].items():
        operation = hook["post"]
        body = resolve(operation["requestBody"])["content"]["application/json"]["schema"]
        properties = resolve(body)["properties"]
        envelopes[operation["operationId"]] = properties
        fields(identifier(operation["operationId"]) + "Body", properties)
    # ParseEnvelope intentionally shares the scored descriptors with ping and unknown events.
    # That is safe only while both documented envelope shapes expose these same string fields.
    for operation in ("identificationScored", "webhookPing"):
        properties = envelopes.get(operation, {})
        for field in ("event_type", "schema_version", "created_at"):
            if field not in properties or kind(properties[field]) != "string":
                raise UnsupportedContract(f"{operation}: incompatible common envelope field {field}; update the SDK parser")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=ROOT / "resources/shieldlabs-api.yaml")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate(yaml.safe_load(args.spec.read_text(encoding="utf-8")))
    if args.check:
        # Git may use CRLF on Windows; line endings do not change the generated contract.
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
            sys.exit("Generated wire contract is stale; run python3 scripts/generate-wire.py")
    else:
        args.output.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
